### ISSUE TITLE
Add a custom message after the spinner

### ISSUE THREAD

**Issue by curio-sitas** [AshlinHarris/Spinners.jl#60]
It would be great to add a static or dynamic custom message at the right if the rolling spinner for more console stylization.
Even better if we can add an advancement information ? i dont how

```julia
julia> spinner(:clock, msg = "Loading universe")
⏱️ Loading universe
```

**Comment by AshlinHarris** [comment]
Agreed. Version 0.2 had this feature, along with a few other custom options like altering the speed.

One temporary workaround would be to include the message inside every frame of the spinner.
