### ISSUE TITLE
Spinner arguments should be parsed

### ISSUE THREAD

**Issue by AshlinHarris** [AshlinHarris/Spinners.jl#72]
Currently, users can supply the following spinner parameters:
- style
- seconds per frame
- before message
- after message

At the end of the list, an expression is required.

Example: ` @spinner :clock 0.1 "LOADING" "..." sleep(5)`

Default arguments are provided by `timer_spin` in a lazy way (My bad!). It is assumes the first argument is style, the second is the framerate, etc. So we have
```
@spinner :pong sleep(4)     # possible
@spinner :pong 0.1 sleep(4) # possible
@spinner 0.1 sleep(4)       # error
```

What inputs should be accepted? Some possibilities:
```
@spinner f()
@spinner :pong f()
@spinner 0.1 f()
@spinner :pong 0.1 f()
@spinner :clock msg="LOADING " f()
```
What order of arguments should be accepted, and how can they be parsed by type?

**Comment by curio-sitas** [comment]
I think the most used argument should be the style and the custom message.
So i would suggest to put the framerate at the end, before the `Expr`.

Also spinner is good for rapid and easy use and this suggests not to have much customization. On the other hand the function does not give the scope...

**Comment by AshlinHarris** [comment]
That makes sense.

Should `style` always take priority over `msg`? That is, should `@spinner some_string f()` assume that `some_string` is a style, not a message? Alternatively, we could assume the first `Symbol` is a style, the first`String` is a message, and the first `Number` is a framerate.

Each of these arguments could be optional with a default value supplied. Any other argument (preceding message, mode) could be an named argument (e.g., `mode=:random`).

**Comment by curio-sitas** [comment]
> That makes sense.
> 
> Should `style` always take priority over `msg`? That is, should `@spinner some_string f()` assume that `some_string` is a style, not a message? Alternatively, we could assume the first `Symbol` is a style, the first`String` is a message, and the first `Number` is a framerate.
> 
> Each of these arguments could be optional with a default value supplied. Any other argument (preceding message, mode) could be an named argument (e.g., `mode=:random`).

Isn't it to complicated and confusing to have different argument order based on the style type ?
