### ISSUE TITLE
`@spinner` does not consider spinner type (symbol) anymore

### ISSUE THREAD

**Issue by curio-sitas** [AshlinHarris/Spinners.jl#88]
`@spinner` macro prints the default spinner despite the fact that another spinner is asked
![test](https://user-images.githubusercontent.com/26415466/197365783-4d978d9c-a1dd-4fe9-a871-ae3287746fb3.gif)

**Comment by AshlinHarris** [comment]
Sorry about that! I've been testing things manually for now, and I missed this issue.

Once I rewrite the drawing functions to use cursor locations instead of backspaces, I can rewrite the test suite to make sure this doesn't happen anymore.
